list = ['mango', 'banana', 'cherry', 11, 25.5, True]
print(list)
print('type', type(list))
print('length', len(list))
print('first element', list[0])
print('fourth element', list[3])
print('last element', list[-2])
print('slice', list[1:4])
print('append', list.append('orange'))
print(list)
print('remove', list.remove(11))
print(list)
print('insert', list.insert(2, 'kiwi'))
print(list)
print('pop', list.pop())
print(list)
print('index of banana', list.index('banana'))
print('count of cherry', list.count('cherry'))
print('sort', list.sort(key=str))
print(list)
print('reverse', list.reverse())
print(list)
# print('clear', list.clear())
print(list)
print('is empty', len(list) == 0)
print('concatenate', list + ['grape', 'melon'])
print('repeat', ['apple'] * 3)
print('iterate')
for item in ['a', 'b', 'c']:
    print(item)
print('nested list', [[1, 2], [3, 4], [5, 6]])
nested_list = [[1, 2], [3, 4], [5, 6]]
print('first element of first nested list', nested_list[0][0])