name = "hello"

# print((name[1]))  
print(name.startswith("h"))
print(name.endswith("O"))
print(len(name))
print(name.replace("l", "p"))
print(name.upper())
print(name.lower())
print(name.capitalize())
print(name.find("e"))
print(name.count("l"))
print(name*3)
print(name[0:4])
print(name[::-1])
print(name.split("e"))
print(name.isalpha())
print(name.isnumeric())
print(name.index("o"))
print(name.center(20, "*"))
print(name.swapcase())
print(name.title())
print(name.encode())
print(name.partition("e"))
print(name.ljust(20, "-"))
print(name.rjust(20, "-"))
print(name.zfill(20))
print(name.strip("h"))
print(name.format())
print(name.translate(str.maketrans("h", "j")))
print(name.removeprefix("he")) 